config/routes.rb
TestRails5::Application.routes.draw do
  resources :events

  resources :users

  match '/calendar(/:year(/:month))'        => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  

end

app/models/event.rb
# coding: utf-8

class Event < ActiveRecord::Base
  #has_event_calendar
  
  attr_accessible :user_id, :start_at, :end_at, :state
  
  belongs_to  :user

  # def before_save # before_saveメソッドはActiveRecordの機能で、保存前に自動的に呼び出されるコールバックメソッドである。
  #   self.start_at ||= Date.today
  # end
  
  # def before_save
  #   self.state = true
  # end


end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base
  attr_accessible :name
  
  # バリデーション
  # nameが空でないか検証
  #validates_presence_of :name
  # nameが2文字以上30文字以下であることを検証
  # validates_length_of :name, :in => (2..30),
  #     :too_short => "nameは2文字以上で入力してください。",
  #     :too_long  => "nameは30文字以下で入力してください。"
  #validates :name, :presence => true, :length => 2..30
  
  validates :name, :presence => true
  has_many :events
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.event_strips_for_month(@shown_month)
    
    @test=action_name
  end

%#
  def test
    @month=(params[:month] || (Time.zone || Time).now.month).to_i
  end
%#

end

app/controllers/events_controller.rb
class EventsController < ApplicationController  
  # GET /events
  # GET /events.json
  
  # # ブラウザの言語設定で判定する場合
  # before_filter :set_locale
  # def set_locale
  #   I18n.locale  request.env['HTTP_ACCEPT_LANGUAGE'].split(",").first
  # end

  
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
    
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    # flash[:notice]="Wellcome...!"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        # newアクションのテンプレートを描画する
        format.html { render action: "new", :layout => "error_warning" }  # format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
# encoding:utf-8

module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>" #,
      #:show_today => @show_today
      #:show_header => @show_header


    }
  end

  def event_calendar(time)
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
    
      event = args[:event]
      
      #html = %(<a href="/events/#{event.id}" title="#{h(event.user.name)}">#{h(event.user.name)})

      if event.start_at < time
        if event.state == true
          #html << %( : <font size=3>◯</font></a>)
          html = %(<a href="/events/#{event.id}" title="#{h(event.user.name)}, ◯">#{h(event.user.name)} : ◯</a>)
        elsif event.state == false
          #html << %( : <font size=3>×</font></a>)
          html = %(<a href="/events/#{event.id}" title="#{h(event.user.name)}, ×">#{h(event.user.name)} : ×</a>)
        else
          #html << %( : error</a>)
          html = %(<a href="/events/#{event.id}" title="#{h(event.user.name)}, error">#{h(event.user.name)} : error</a>)
        end
      else
        #html << %( : -</a>)
        html = %(<a href="/events/#{event.id}" title="#{h(event.user.name)}, -">#{h(event.user.name)} : -</a>)
      end
            

      #%(<a href="/events/#{event.id}" title="#{h(event.user.name)}, #{event.state}">#{h(event.user.name)} : #{h(event.state)}</a>)
      
      #html = %(<scrit type="text/javascript">)
      #concat capture(Time.now)
       
      
      #event, day = args[:event], args[:day], args[:options]
      #html = %(<a href="/events/#{event.id}" title="#{h(event.user_id)}">)
      #html << display_event_time(event, day)
      #html << %(, #{h(event.user_id)}</a>)
      #html

    end
  end

    
  
  def link_to_unless_current_action(label, url_option={})
    # リンク先が現在のアクションかどうかを確認し、フラグを立てる
    target_is_current_page=(
      (url_option[:controller]=="users") &&
      (url_option[:action]=="index"))
      # link_to_unlessメソッドを使い、上での確認結果に基づきリンクを生成する
    link_to_unless(target_is_current_page, label, url_option)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendar/index.html.erb
# coding: utf-8

<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<% @shown_month %>	<%# output:2012-06 %>
<% @shown_month.month %>	<%# output:6 %>
<%#<% @shown_month.year %>	<%# output:2012 %>
<%#<% @shown_month.day %>	<%# output:1 %>
<%#<% @event_strips %>

<%# output:
[[nil, nil, nil, nil, nil, #<Event id: 1, user_id: 1, start_at: "2012-06-01 11:07:00", end_at: "2012-06-01 11:07:00", state: true, created_at: "2012-06-05 11:09:04", updated_at: "2012-06-05 11:32:21">, #<Event id: 2, user_id: 2, start_at: "2012-06-02 11:17:00", end_at: "2012-06-02 11:17:00", state: false, created_at: "2012-06-05 11:17:48", updated_at: "2012-06-05 11:17:48">, #<Event id: 3, user_id: 3, start_at: "2012-06-03 11:17:00", end_at: "2012-06-03 11:17:00", state: false, created_at: "2012-06-05 11:18:01", updated_at: "2012-06-05 11:18:01">, #<Event id: 4, user_id: 4, start_at: "2012-06-04 11:17:00", end_at: "2012-06-04 11:17:00", state: true, created_at: "2012-06-05 11:18:08", updated_at: "2012-06-05 12:28:51">, #<Event id: 5, user_id: 5, start_at: "2012-06-05 11:17:00", end_at: "2012-06-05 11:17:00", state: true, created_at: "2012-06-05 11:18:15", updated_at: "2012-06-06 01:18:25">, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil]]
%>

<%#<% @month %> <%# output:6 %>
<%#<% @year %> <%# output:2012%>
<%#<% @show_today %> <%# output:%>


<h1>Calendar</h1>

<% @user = User.new %>
<% t = Time.now %>
<% @time = Time.local(t.year, t.month, t.day, 9, 0, 1) %>
<%# @time = Time.local(t.year, 6, 11, 9, 0, 1) %>
<%= raw(event_calendar(@time)) %><br />

<%#= event_calendar_opts %>

<%#<%= @shown_month.prev_month.month %> <!-- 前月 -->

<!-- eventsテーブル 登録usersリスト -->
<!-- <b>[ eventsテーブル 登録usersリスト ]</b><br /> -->
<!-- <%# events = Event.all %> -->
	<!-- <%# events.each do |event| %> -->
	<%#<%= event.id %> <!-- : <%#= event.user.name %><br /> -->
	<!-- <%#= event.start_at.year %> / <%#= event.start_at.month %> / <%#= event.start_at.day %> : <%#= event.user.name%> , <%#= event.state %><br />
<%# end %>
<br /> -->



<!-- eventsテーブル 登録users(state=NG)リスト -->
<b>[ eventsテーブル 登録users(state=NG)リスト ]</b><br />
<%# t = Time.now %>
<table>
<%# events = Event.all %>
<% events = Event.order("start_at DESC") %>
<% events.each do |event| %>
	<% if event.state == false %>
		<%# if (event.start_at.month <= Time.now.month) and (event.start_at.year <= Time.now.year)%> <!-- こちらでは、日付の指定がややこしくなう上、難しく複雑になるので、使わない -->
		<%# if event.start_at <= Time.now %> <!-- こちらなら、簡単に指定できるので、こちらを使う -->
		<%# if (event.start_at.year == t.prev_month.year) and (event.start_at.month == t.prev_month.month) %>
		<%# if (event.start_at.year <= t.year) and (event.start_at.month <= t.month) and (event.start_at.day < t.day)%>
		<% if (event.start_at < @time) %>
			<tr>
				<!-- <td><%#= event.start_at.year %></td>		<td> /</td> -->
				<!-- <td><%#= event.start_at.month %></td>	<td>/</td> -->
				<!-- <td><%#= event.start_at.day %></td>		<td>:</td> -->
				<td><%= event.start_at.to_date %></td>	<td>:</td>
				<td><%= event.user.name %></td>				<td>,</td>
				<!-- <td><%#= event.state %></td> -->
				<td>
					<% if event.state == true %> OK
					<% elsif event.state == false %> NG
					<% else %> error
					<% end %>
				</td>
			</tr>
		<% end %>
		<% if (@time.day == event.start_at.day) %>
			<tr><td>--------------</td><td>--</td><td>----------</td><td>--</td><td>-----</td></tr>
		<% end %>
	<% end %>
<% end %>
</table>
<br /><br />

<!-- <%= t = Time.now %> (now)<br /> -->	<!-- 現在 -->
<%# t = Time.local(t.year, t.month, t.day)%>
<!-- <%= t.yesterday %> (yesterday)<br /> -->	<!-- 昨日 -->
<!-- <%= t.tomorrow %> (tomorrow)<br /> -->		<!-- 明日 -->
<!-- <%= t.prev_month.year %> (prev month)<br /> -->	<!-- 昨月 -->
<!-- <%= t.next_month %> (next month)<br /> -->	<!-- 来月 -->
<!-- <%= t.prev_year %> (prev year)<br /> -->	<!-- 昨年 -->
<!-- <%= t.next_year %> (next year)<br /> -->	<!-- 来年 -->

<!--<b>[ 前月の未実施者 ]</b>-->
<%# events = Event.all %>
	<%#<% events.each do |event| %>
		<%#<% t = Time.now %>	<!-- now -->
		<%#<% if (event.start_at.year  == t.prev_month.year ) and (event.start_at.month == t.prev_month.month) %>		<!--t.prev_month.year:前月の西暦、 t.prev_month.month:前月の月 -->
			<!--<%#<%= event.start_at.year %> / <%#<%= event.start_at.month %> / <%#<%= event.start_at.day %>--><!--<br />-->
		<%#<% end %>
	<%#<% end %>
<%# end %>

app/views/events/edit.html.erb
# coding:utf-8

<%# I18n.locale = :ja %>

<%- model_class = @event.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
# coding: utf-8

<% I18n.locale = :ja %>
<%- model_class = Event.new.class -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><%#= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:start_at) %></th>
      <th><%= model_class.human_attribute_name(:end_at) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <!-- <th><%#= model_class.human_attribute_name(:created_at) %></th> -->
			<th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
		<% @events = Event.order("start_at DESC")%>
    <% @events.each do |event| %>
		<% t = Time.local(Time.now.year, Time.now.month, Time.now.day, 9, 0, 1) %>
      <tr>
        <!-- <td><%#= link_to event.id, event_path(event) %></td> -->
        <td><%= link_to event.user.name, event_path(event) %><%#= event.user_id %></td>

        <td><%= event.start_at.to_date %>	<!-- <td><%= event.start_at.year %> / <%= event.start_at.month %> / <%= event.start_at.day %></td> -->	<!-- <td><%#= event.start_at. %></td> -->
				<td><%= event.end_at.to_date %></td>	<!-- <td><%= event.end_at.year %> / <%= event.end_at.month %> / <%= event.end_at.day %></td> -->	<!-- <td><%= event.end_at %></td> -->
        <!-- <td><%= event.state %></td> -->
				<td>
				<% if event.start_at < t %>
					<% if event.state == true %>OK<!-- <font size=2>◯</font> -->
					<% elsif event.state == false %>NG<!-- <font size=3>×</font> -->
					<% else %>error
					<% end %>
				<% else %><font size=3>-</font>
				<% end %>
				
				</td>
        <!-- <td><%#=l event.created_at %></td> -->
				<!-- <td><%#= event.created_at %></td> -->
				<td><%= event.updated_at.to_s(:db) %></td>	<!-- <td><%#= event.updated_at.year %> / <%#= event.updated_at.month %> / <%#= event.updated_at.day %></td> -->
				
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

<br /><br />


<!-- eventsテーブル 登録users(state=false)リスト -->
<b>[ eventsテーブル 登録users(state=false)リスト ]</b><br />
<% t = Time.now %>
<%# t = Time.local(2012, 7, 2)%>
<table>
	<%# events = Event.all %>
	<% events = Event.order("start_at DESC") %>
	<% events.each do |event| %>
		<% if event.state == false %>
			<%# if (event.start_at.month <= Time.now.month) and (event.start_at.year <= Time.now.year)%> <!-- こちらでは、日付の指定がややこしくなう上、難しく複雑になるので、使わない -->
			<%# if event.start_at <= Time.now %> <!-- こちらなら、簡単に指定できるので、こちらを使う -->
			<%# if (event.start_at.year == t.prev_month.year) and (event.start_at.month == t.prev_month.month) %>
			<%# if (event.start_at.year <= t.year) and (event.start_at.month <= t.month) and (event.start_at.day < t.day)%>
			<% if (event.start_at < t) %>
				<tr>
					<!-- <td><%= event.start_at.year %></td>		<td>/</td> -->
					<!-- <td><%= event.start_at.month %></td>	<td>/</td> -->
					<!-- <td><%= event.start_at.day %></td>		<td>:</td> -->
					
					<td><%= event.start_at.to_date %></td>	<td>:</td>
					<td><%= event.user.name %></td>				<td>,</td>
					<td>
						<% if event.state == true %> OK
						<% elsif event.state == false %> NG
						<% else %> error
						<% end %>
					</td>
				</tr>
			<% end %>
			<% if (t.day == event.start_at.day) %>
				<tr><td>--------------</td><td>--</td><td>----------</td><td>--</td><td>-----</td></tr>
			<% end %>
		<% end %>
	<% end %>
</table>
<br /><br />

<%= Time.now %><br />
<%= Time.now.to_s(:db) %><br />
<%= Time.now.to_s(:time) %><br />

<% I18n.locale = :ja %>
<%= User.model_name.human %><br />
<%= Event.model_name.human %><br />

<%= User.human_attribute_name("name") %><br />
<%= User.human_attribute_name("created_at") %><br />
<%= Event.human_attribute_name("user_id") %><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TestRails5" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">TestRails5</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Calendar", calendar_path  %></li>
              <li><%= link_to "Events", events_path  %></li>
              <li><%= link_to "Users", users_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Calendar", calendar_path  %></li>
                  <li><%= link_to "Events", events_path  %></li>
                  <li><%= link_to "Users", users_path  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/_form.html.erb
# coding:utf-8

<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

	<!-- 実行するactionがeditまたはshowの場合（new以外の場合） -->
	<% if action_name != 'new' %>	<!-- 左記あるいは右記 -->	<%# if (action_name == 'edit') or (action_name == 'show') %>
  	<div class="control-group">
    	<%= f.label :created_at, :class => 'control-label' %>
    	<div class="controls">
				<%= @user.created_at.to_date %>
    	</div>
  	</div>

 		<div class="control-group">
    	<%= f.label :updated_at, :class => 'control-label' %>
    	<div class="controls">
				<%= @user.updated_at.to_date %>
    	</div>
  	</div>
	<% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
# coding:utf-8

<% I18n.locale = :ja %>

<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
# coding:utf-8

<% I18n.locale = :ja %>

<%- model_class = User.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><%#= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:name) %></th>
			<th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
			<th>Penalty_count</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
		<% t = Time.now %>
		<% @users = User.order("updated_at ASC")%>
    <% @users.each do |user| %>

     	<tr>
        <!-- <td><%# link_to user.id, user_path(user) %></td> -->
        <td><%= link_to user.name, user_path(user) %></td>

				<td><%= user.created_at.to_date %></td>
				
        <!-- <td><%#=l user.created_at %></td> -->
				<!-- <td><%#= user.updated_at.year %> / <%#= user.updated_at.month %> / <%#= user.updated_at.day %></td> -->
				<td><%= user.updated_at.to_date %></td>
				
				<!-- 掃除を行わなかった回数をペナルティ・カウントとして数える -->
				<% penalty_count = 0%>
				<!-- eventsテーブルからレコードを全て取り出し、eventsに格納する -->
				<% events = Event.all %>
				<!-- eventsに格納したレコードを1つずつ取り出し、eventという名前で扱う -->
				<% events.each do |event| %>
					<!-- 掃除日程が現在日より以前の場合 -->
					<% if event.start_at.to_date < t.to_date %>		
						<!-- 掃除作業者が作業者と同じ場合 -->
						<% if event.user_id == user.id %>
							<!-- 掃除が行われなかった場合 -->
							<% if event.state == false%>
								<!-- ペナルティ・カウントを1増やす -->
								<% penalty_count = penalty_count + 1 %>
							<% end %>
						<% end %>
					<% end %>
	 			<% end %>
				<!-- ペナルティ・カウントを表示する -->
				<td><%= penalty_count %></td>
				
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

<br />
<% user_without_name = User.new %>
<%= user_without_name.valid? %><br />

<%= user_without_name.errors %><br />

<% user_without_name.errors.each do |attribute, error| %>
<%= "#{attribute} have errors '#{error.to_s}'."%><br />
<% end %>

<%= user_without_name.errors.full_messages %><br />

<%= user_without_name.errors.count %><br />

app/views/users/new.html.erb
# coding:utf-8

<% I18n.locale = :ja %>

<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>